apiVersion: v1
kind: Service
metadata:
  name: mongo-analytics
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mongo-analytics
  ports:
  - port: {{ .Values.mongoAnalytics.port }}
    targetPort: {{ .Values.mongoAnalytics.port }}
  type: ClusterIP