apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: grafana
  ports:
  - port: {{ .Values.grafana.port }}
    targetPort: {{ .Values.grafana.port }}
  type: ClusterIP