apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: tripplanner
type: Opaque
stringData:
  AUTH_DB_PASSWORD: "auth_password"
  AUTH_JWT_SECRET: "change_me_auth_secret_super_long_random_string"
  TRIP_DB_PASSWORD: "trip_password"
  TRIP_JWT_SECRET: "change_me_auth_secret_super_long_random_string"
  GEOAPIFY_API_KEY: "change_me"
  WEATHER_API_KEY: "change_me"